### ISSUE TITLE
Bug Blender 3.2.1

### ISSUE THREAD

**Issue by DeadSue** [RT-studios/camera-pnpoint#1]
Hi. I'm have a bug
if i recreate callibrate camera
blender 3.2.1

Python: Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\camera_pnp\__init__.py", line 74, in execute
    return camcalib(*getsceneinfo(self, context))
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\camera_pnp\campnp.py", line 174, in camcalib
    ret, camintr, distcoef, _, _ = cv.calibrateCamera(np.asarray([points3d], dtype='float32'), 
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\calibration.cpp:1550: error: (-211:One of the arguments' values is out of range) Principal point must be within the image in function 'cvCalibrateCamera2Internal'

**Comment by RT-studios** [comment]
Hi, 
I cannot reproduce this issue, could you provide more details? which lens parameters where activated to calibrate, and did you edit any parameter manually in the Track/Camera tab?
Thanks

**Comment by DeadSue** [comment]
hi. yes. i can edit parameter manually. `Python: Traceback (most recent call last):

this error when I move the tracker and then click camera calibration

**Comment by DeadSue** [comment]
this error, I don't know why, I seem to have done everything as usual, a collection with blanks and trackers, I first put 1 blank and 1 tracker and repeat as many times as necessary for the best result, before that i successfully set up about 10 cameras without errors, there were 230+ empty objects in the scene, i deleted them all and tried to set up a new camera and this error popped up

Python: Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\camera_pnp\__init__.py", line 61, in execute
    return solvepnp(*getsceneinfo(self, context)) 
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\camera_pnp\campnp.py", line 102, in solvepnp
    ret, rvec, tvec, error = cv.solvePnPGeneric( points3d
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\sqpnp.cpp:242: error: (-215:Assertion failed) point_coordinate_variance >= POINT_VARIANCE_THRESHOLD in function 'cv::sqpnp::PoseSolver::computeOmega'

**Comment by DeadSue** [comment]
![image](https://user-images.githubusercontent.com/73847765/181292197-094971a8-1dac-4215-967e-47204c38c6d7.png)

and created many camers:)

**Comment by RT-studios** [comment]
Hi, 
this last error is new to me, but it sounds like the input points might be in an odd arrangement difficult to solve. If you can share an example file where I can reproduce the issue that would be super helpful.
And by the way if you are trying to fine-tune one specific camera, make sure to select it before solving the pose, this way it will not create new cameras every time (unless that´s your intention of course ;-)
