### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by DeadSue** [RT-studios/camera-pnpoint#4]
Python: Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\camera_pnp\__init__.py", line 74, in execute
    return camcalib(*getsceneinfo(self, context))
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\camera_pnp\campnp.py", line 60, in getsceneinfo
    points2d.append([track.markers[fr].co[0]*size[0],
IndexError: bpy_prop_collection[index]: index 1 out of range, size 1

**Comment by RT-studios** [comment]
Hi, could you share a .blend or instructions to reproduce this one on my end?
Thanks!
