### ISSUE TITLE
Attempting a solve gives "Array iterator out of range"

### ISSUE THREAD

**Issue by alinsavix** [RT-studios/camera-pnpoint#9]
Attempting to do a camera calibrate or camera solve w/ v0.0.6 is giving me the following trace:

```
Array iterator out of range: (index 911)
Traceback (most recent call last):
  File "C:\Users\alinsa\AppData\Roaming\Blender Foundation\Blender\scripts\addons\camera_pnp\__init__.py", line 74, in execute
    return camcalib(*getsceneinfo(self, context))
  File "C:\Users\alinsa\AppData\Roaming\Blender Foundation\Blender\scripts\addons\camera_pnp\campnp.py", line 60, in getsceneinfo
    points2d.append([track.markers[fr].co[0]*size[0],
IndexError: bpy_prop_collection[index]: index 911 out of range, size 1
Error: Python: Traceback (most recent call last):
  File "C:\Users\alinsa\AppData\Roaming\Blender Foundation\Blender\scripts\addons\camera_pnp\__init__.py", line 74, in execute
    return camcalib(*getsceneinfo(self, context))
  File "C:\Users\alinsa\AppData\Roaming\Blender Foundation\Blender\scripts\addons\camera_pnp\campnp.py", line 60, in getsceneinfo
    points2d.append([track.markers[fr].co[0]*size[0],
IndexError: bpy_prop_collection[index]: index 911 out of range, size 1
```

Tried on both 3.5 and 3.6 with the same results. This is with 8 points set up as the documentation suggests, and correctly ordered. Blend file is attached. Help?

[Logo Animation.zip](https://github.com/RT-studios/camera-pnpoint/files/13707016/Logo.Animation.zip)

**Comment by RT-studios** [comment]
Hello,
first  of all, my apologies for the long delay - I have been off-line for a couple of weeks.

What you describe is unfortunately a known bug caused by the current animation frame not being the first. One possible workaround for you is to simply set the animation to frame 1, perform the solve and, if required, then move back to the desired frame and keyframe the solved camera transform.

RT

**Comment by RT-studios** [comment]
This bug is hopefully fixed now in [v0.0.7](https://github.com/RT-studios/camera-pnpoint?tab=readme-ov-file#version-history)
